version: "3.7"
services:
  tensorflow-jupyter:
    build:
      context: .
    # enable gpu usage
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 127.0.0.1:8888:8888
      # - 127.0.0.1:46624:46624
    volumes:
      - ./data:/tf
      - ./jupyter:/root/.jupyter
    restart: always